export const TOKEN_BAD = "TOKEN_BAD";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const USER_ALREADY_EXISTED = "USER_ALREADY_EXISTED";
export const INTERNAL_DB = "INTERNAL_DB";
export const INVALID_AUTH_CODE = "INVALID_AUTH_CODE";
